sbatch slurms/slurm1.script
sbatch slurms/slurm1.script
sbatch slurms/slurm1.script
sbatch slurms/slurm1.script
sbatch slurms/slurm1.script
sbatch slurms/slurm1.script
sbatch slurms/slurm1.script
sbatch slurms/slurm1.script
sbatch slurms/slurm1.script
sbatch slurms/slurm1.script
