sbatch slurms/slurm1-1.script
sbatch slurms/slurm1-2.script
sbatch slurms/slurm1-3.script
sbatch slurms/slurm1-4.script
sbatch slurms/slurm1-5.script
sbatch slurms/slurm1-6.script
sbatch slurms/slurm1-7.script
sbatch slurms/slurm1-8.script
sbatch slurms/slurm1-9.script
sbatch slurms/slurm1-10.script
sbatch slurms/slurm1-11.script
sbatch slurms/slurm1-12.script
sbatch slurms/slurm1-13.script
sbatch slurms/slurm1-14.script
sbatch slurms/slurm1-15.script
sbatch slurms/slurm1-16.script
sbatch slurms/slurm1-17.script
sbatch slurms/slurm1-18.script
sbatch slurms/slurm1-19.script
sbatch slurms/slurm1-20.script
sbatch slurms/slurm1-21.script
sbatch slurms/slurm1-22.script
sbatch slurms/slurm1-23.script
sbatch slurms/slurm1-24.script
sbatch slurms/slurm1-25.script
sbatch slurms/slurm1-26.script
sbatch slurms/slurm1-27.script
sbatch slurms/slurm1-28.script
sbatch slurms/slurm1-29.script
sbatch slurms/slurm1-30.script
sbatch slurms/slurm1-31.script
sbatch slurms/slurm1-32.script
sbatch slurms/slurm1-33.script
sbatch slurms/slurm1-34.script
sbatch slurms/slurm1-35.script
sbatch slurms/slurm1-36.script
sbatch slurms/slurm1-37.script
sbatch slurms/slurm1-38.script
sbatch slurms/slurm1-39.script
sbatch slurms/slurm1-40.script
sbatch slurms/slurm1-41.script
sbatch slurms/slurm1-42.script
sbatch slurms/slurm1-43.script
sbatch slurms/slurm1-44.script
sbatch slurms/slurm1-45.script
sbatch slurms/slurm1-46.script
sbatch slurms/slurm1-47.script
sbatch slurms/slurm1-48.script
sbatch slurms/slurm1-49.script
sbatch slurms/slurm1-50.script
sbatch slurms/slurm1-51.script
sbatch slurms/slurm1-52.script
sbatch slurms/slurm1-53.script
sbatch slurms/slurm1-54.script
sbatch slurms/slurm1-55.script
sbatch slurms/slurm1-56.script
sbatch slurms/slurm1-57.script
sbatch slurms/slurm1-58.script
sbatch slurms/slurm1-59.script
sbatch slurms/slurm1-60.script
sbatch slurms/slurm1-61.script
sbatch slurms/slurm1-62.script
sbatch slurms/slurm1-63.script
sbatch slurms/slurm1-64.script
sbatch slurms/slurm1-65.script
sbatch slurms/slurm1-66.script
sbatch slurms/slurm1-67.script
sbatch slurms/slurm1-68.script
sbatch slurms/slurm1-69.script
sbatch slurms/slurm1-70.script
sbatch slurms/slurm1-71.script
sbatch slurms/slurm1-72.script
sbatch slurms/slurm1-73.script
sbatch slurms/slurm1-74.script
sbatch slurms/slurm1-75.script
sbatch slurms/slurm1-76.script
sbatch slurms/slurm1-77.script
sbatch slurms/slurm1-78.script
sbatch slurms/slurm1-79.script
sbatch slurms/slurm1-80.script
sbatch slurms/slurm1-81.script
sbatch slurms/slurm1-82.script
sbatch slurms/slurm1-83.script
sbatch slurms/slurm1-84.script
sbatch slurms/slurm1-85.script
sbatch slurms/slurm1-86.script
sbatch slurms/slurm1-87.script
sbatch slurms/slurm1-88.script
sbatch slurms/slurm1-89.script
sbatch slurms/slurm1-90.script
sbatch slurms/slurm1-91.script
sbatch slurms/slurm1-92.script
sbatch slurms/slurm1-93.script
sbatch slurms/slurm1-94.script
sbatch slurms/slurm1-95.script
sbatch slurms/slurm1-96.script
sbatch slurms/slurm1-97.script
sbatch slurms/slurm1-98.script
sbatch slurms/slurm1-99.script
sbatch slurms/slurm1-100.script
